### ISSUE TITLE
New Version did not start no connection

### ISSUE THREAD

**Issue by tobasium** [Zefau/ioBroker.plex#10] opened 2019-08-15 21:50 UTC
After Update to the new version no connection to plesk on the same server.

**Comment by Zefau** [comment] 2019-08-16 18:32
What version are you on and which one are you coming from?
Please change the adapter to debug (via interfaces -> expert modus) and provide the log.

**Comment by tobasium** [comment] 2019-08-16 18:59
Hello I am on 0.4.0 want to go to 0.4.3
[iobroker.2019-08-16.log.zip](https://github.com/Zefau/ioBroker.plex/files/3510810/iobroker.2019-08-16.log.zip)

**Comment by Zefau** [comment] 2019-08-18 19:35
@tobasium Are you still having the error? Simply restart your machine and it should be fixed.

The problem is caused by the adapter running twice for some reason, which blocks the port (error `EADDRINUSE`).

**Comment by tobasium** [comment] 2019-08-18 20:13
Update to version 0.4.4 still the issue new log 
[iobroker.2019-08-18.log.zip](https://github.com/Zefau/ioBroker.plex/files/3513528/iobroker.2019-08-18.log.zip)

**Comment by Zefau** [comment] 2019-08-18 20:35
Did you provide a plex user and password in the adapter settings?

**Comment by tobasium** [comment] 2019-08-18 20:41
Yes i Have a plex pass and yes I have a pin and provide in adapter settings. The fact is if i change anything the adapter is for seconds green and then directly red.

**Comment by Zefau** [comment] 2019-08-18 20:54
It is an error in the adapter, which can't handle PIN protection yet. I will add support in the next release.
Try this workaround for now: https://github.com/Zefau/ioBroker.plex#21-basic-setup

**Comment by Zefau** [comment] 2019-08-20 18:14
Please install current Github Version v0.6.0, which should fix the error. With this version you are able to retrieve a Plex Token (instead of using a password).

**Comment by tobasium** [comment] 2019-08-20 19:37
Hi,

I will check if i see the update on iobroker. actually is 0.5.0

**Comment by Zefau** [comment] 2019-08-20 19:45
It is not available so far on iobroker. You have to install it manually via `Adapters` by the icon saying `Install from custom URL` and paste the Github URL `https://github.com/Zefau/ioBroker.plex`.

**Comment by tobasium** [comment] 2019-08-20 19:50
Hi don't work for me don't know why. My iobroker is in a docker image on my synology nas in network bridge. Maybe the problems are therefrom. But other things work with the normal IP. Also adapter 0.4.0 was green also.

**Comment by tobasium** [comment] 2019-08-20 19:55
I restart the container and know it looks a little bit better: the plex is yellow but did not recive a pin

**Comment by Zefau** [comment] 2019-08-20 20:13
When you request a PIN in the interface configuration, do you get any error messages in the Log?

**Comment by Zefau** [comment] 2019-08-20 20:14
Could you change the interface to debug? Via `Interfaces` --> Button `Expert mode` and the changing `info` to `debug`.

**Comment by tobasium** [comment] 2019-08-20 20:16
warn: plex.0 Plex IP and Plex Token not configured! Please go to settings, fill in Plex IP and retrieve a Plex Token

[iobroker.2019-08-20.log.zip](https://github.com/Zefau/ioBroker.plex/files/3522419/iobroker.2019-08-20.log.zip)

**Comment by Zefau** [comment] 2019-08-20 20:17
Did you go into the Plex Interface configuration to retrieve a token?

**Comment by Zefau** [comment] 2019-08-20 20:18
![Capture](https://user-images.githubusercontent.com/14368811/63381155-68128400-c398-11e9-909a-b8f1018f314d.PNG)

**Comment by tobasium** [comment] 2019-08-20 20:21
Yes,
There is this error.
Keine Verbindung zum Adapter! Bitte zunächst den Adapter starten.
No connection to adapter! Please start adapter

**Comment by Zefau** [comment] 2019-08-20 20:27
When you press the button `Get a token` you should see a popup with a PIN. Is that correct or what happens?

**Comment by Zefau** [comment] 2019-08-20 20:27
ah sorry, now I understand

**Comment by Zefau** [comment] 2019-08-20 20:29
Could you upload the adapter by the button?
![Capture](https://user-images.githubusercontent.com/14368811/63381936-f9cec100-c399-11e9-867b-af02cf355afe.PNG)

**Comment by tobasium** [comment] 2019-08-20 20:30
yes i have

**Comment by tobasium** [comment] 2019-08-20 20:34
ok know i get a code but in the log a warn:

Plex Server denied request, you must provide a way to authenticate! Read more about plex-api authenticators on https://www.npmjs.com/package/plex-api#authenticators

**Comment by Zefau** [comment] 2019-08-20 20:35
So you successfully retrieved a token, but this is not enough for the adapter? :-\

**Comment by tobasium** [comment] 2019-08-20 20:38
After i recive token and enter it on the side nothing happens on iobroker.

in the plex options i see a new linked hardware:

Plex for ioBroker
vor 4 Minuten
Plex for ioBroker

**Comment by tobasium** [comment] 2019-08-20 20:41
ok i get it after do it 4 times

**Comment by tobasium** [comment] 2019-08-20 20:43
It works know. Thanks for your work and your time

**Comment by Zefau** [comment] 2019-08-20 20:43
Ok, great! :)

**Closed** 2019-08-20 20:44 UTC
